[SERVICE]
    Flush        1
    Daemon       Off
    Log_Level    debug
    Parsers_File parsers.conf

[INPUT]
    Name       tail
    Path       /logs/login.log
    Parser     json
    Tag        login

[OUTPUT]
    Name       forward
    Match      login
    Host       fluentd
    Port       24224