version: '3.7'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - 9200:9200
    volumes:
      - /home/ubuntu/elk-stack/esdata:/usr/share/elasticsearch/data

  logstash:
    image: docker.elastic.co/logstash/logstash:8.13.4
    volumes:
      - /home/ubuntu/elk-stack/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - /home/ubuntu/elk-stack/logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - 5044:5044
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.4
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
      
  filebeat:
    image: docker.elastic.co/beats/filebeat:8.13.4
    user: root
    depends_on:
      - logstash
    volumes:
      - /home/ubuntu/elk-stack/logs:/elk-logs:ro
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
    command: filebeat -e --strict.perms=false
    
  metricbeat:
    image: docker.elastic.co/beats/metricbeat:8.13.4
    user: root
    depends_on:
      - elasticsearch
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
      - /:/hostfs:ro
      - ./metricbeat/metricbeat.yml:/usr/share/metricbeat/metricbeat.yml:ro
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    command: metricbeat -e